server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: 1012004
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  signerKey: nnUQNZM9ttoKvWIitvFKhC3cqcHYYeLgwmG4EKdk2WRtxdhpByKZmD90uaA9gIWY
